--DONE: Noise spike at about +0.35 in clip space (only on iPad).
--DONE: CRT block does not scale. Is this underlying layout issues on iOS? (No, it's not the WebGL. What it is?
--DONE: Reduce sorting burden - if that what's slowing the iPad. (It seems to have an impact.)
--DONE: (pass in number of raids, select sort size)
--DONE: Noise parameters to configuration.
--DONE: Treat formations as units, with their intrinsic dancing patterns.
--DONE: IFF.
--DONE: Electronic calculator output.
--TODO: Start raids further out.
--TODO: Go! button resets timer, restarts raids from origin.
--TODO: Narrative and on-screen prompts.
--TODO: Physical knobs!!
