--TODO: Summary page showing actual incoming tracks with user plots overlaid.
--TODO: Store all target locations when user enters Bearing & Range. This may make correlation possible.
--TODO: Store all target locations once a minute anyway.
--TODO: Show tracks as yellow lines, maybe different colour for friendly.
--TODO: Show plots as some kind of symbol.
--TODO: Adjust map calibration for consistency with approx range.
--TODO: Derive some average closeness metric.
--TODO: Add some variation to direction of travel of each raid (they are all due West).
--TODO: Add "more ..." on explanatory popups to display overlaid window with more information. (??)
--TODO: Find nice way to constrain to 14 active aircraft (plus two ground rays). (Perhaps just cull the oldest.)
--TODO: Test on Android tablet !! (Some webkit only CSS tags.)
--TODO: Installable on iOS. -- Probably means getting to grips with Cordova/PhoneGap.
--TODO: Reset WebGL time occasionally as the noise visibly degrades, or fix otherwise.
--TODO: Fit it on 800x600 screen?
